name: RPChat
version: 1.0
main: com.rhein.rpchat.RPChat
api-version: 1.20

softdepend: [Essentials]

commands:
  me:
    description: Roleplay action
  whisper:
    description: Whisper to nearby player

permissions:
  rpchat.staff:
    description: Access to staff chat
    default: op