name: RPChat
version: 1.0
main: com.rhein.rpchat.RPChat
api-version: 1.20

softdepend: [Essentials]

commands:
  rp:
    description: Switch to RP chat mode
  ooc:
    description: Switch to OOC chat mode
  whisper:
    description: Whisper to nearby players
  yell:
    description: Yell to farther players
  looc:
    description: Send a local OOC message
  me:
    description: Send an emote

permissions:
  rpchat.staff:
    description: Access to staff chat
    default: op